Sprint 14
Filosuf/Tracker pull request #1
Opened 2023-02-14 12:50 UTC by Filosuf

2023-02-14 20:34 UTC, IBDesignable requested changes

2023-02-14 20:34 UTC, IBDesignable commented on Tracker/Coordinators/MainCoordinator.swift
> +            return "Статистика"
Я видела, что ты начал использовать файлы локализации. Обычно весь текст для отображения хранится там в формате ключ значение. 

https://habr.com/ru/post/419077/
https://medium.com/swlh/app-localization-in-swift-ios-swift-guide-baa2c2e4298e

2023-02-14 20:34 UTC, IBDesignable commented on Tracker/Coordinators/MainCoordinator.swift
> +    var pageTitle: String {
Можно сложить рядом с координатором

2023-02-14 20:34 UTC, IBDesignable commented on Tracker/Coordinators/MainCoordinator.swift
> +    // показать либо экран авторизации, либо новостную ленту
Если это комментарий на будущее, обычно оформляют как марк, только словом todo: `// TODO: -`

Но пока не понятно зачем тут userEmail

2023-02-14 20:34 UTC, IBDesignable commented on Tracker/Coordinators/MainCoordinator.swift
> +        tabBarVC.setViewControllers(pages.map { getNavController(page: $0) }, animated: true)
красиво конечно, но в погоне за локаничностью обычно еще теряется читаемость: лучше в две строки 
```suggestion
        let viewControllers = TabBarPage.allCases.map { getNavController(page: $0) }
        tabBarVC.setViewControllers(viewControllers, animated: true)
```
TabBarPage можно подписать под протокол `CaseIterable`, чтобы было доступно свойство allCases

2023-02-14 20:34 UTC, IBDesignable commented on Tracker/Coordinators/MainCoordinator.swift
> +final class MainCoordinatorImp: MainCoordinator {
лайк за выбор координатора

2023-02-14 20:34 UTC, IBDesignable commented on Tracker/Models/DayOfWeek.swift
> +    static func <(lhs: DayOfWeek, rhs: DayOfWeek) -> Bool {
```suggestion
    static func < (lhs: DayOfWeek, rhs: DayOfWeek) -> Bool {
```

2023-02-14 20:34 UTC, IBDesignable commented on Tracker/Models/DayOfWeek.swift
> +    static func getWeek() -> [DayOfWeek] {
аналогично, CaseIterable может упростить жизнь здесь

2023-02-14 20:34 UTC, IBDesignable commented on Tracker/Scenes/Trackers Flow/Category settings/CategorySettingsViewController.swift
> +        taps()
setupAction или что-то вроде этого, так не понятно что за нажатия

2023-02-14 20:34 UTC, IBDesignable commented on Tracker/Scenes/Trackers Flow/Category settings/CategorySettingsViewController.swift
> +        }
Новый метод крут, хотя я наверное завидую что в проде такое не использую, поэтому побубню такой рекомендацией: 

Лучше выносить код замыкания в отедельный метод. Так читаемее, легче будет дебажить брекпоинтами, да и селф можно опускать
```suggestion
        saveButton.tapAction = { [weak self] in
            self?.onSaveAction()
        }

     }
     
     private func onSaveAction() {
            let newTitle = nameTextField.text ?? ""
            let newCategories = updateCategories(with: newTitle)
            delegate.categorySettingsDidUpdated(categories: newCategories)
            coordinator.pop()
```

2023-02-14 20:34 UTC, IBDesignable commented on Tracker/Scenes/Trackers Flow/Category settings/CategorySettingsViewController.swift
> +            let categoriesFiltered = categories.filter{$0 != category}
Фигурная скобка не круглая, она не любит когда прилипает к каким-то другим выражениям (по крайней мере по общепринятым гайдам. Здесь и далее в проекте прошу проверить и поправить
```suggestion
            let categoriesFiltered = categories.filter {$0 != category }
```

2023-02-14 20:34 UTC, IBDesignable commented on Tracker/Scenes/Trackers Flow/Category settings/CategorySettingsViewController.swift
> +        var categoriesUpdated = [TrackerCategory]()
Можно вот так. Разницы нет, вкусовщина. Но как то принято отделять тип и значение
```suggestion
        var categoriesUpdated: [TrackerCategory] = []
```

2023-02-14 20:34 UTC, IBDesignable commented on Tracker/Scenes/Trackers Flow/Category settings/CategorySettingsViewController.swift
> +        let isFree = categories.map{$0.title == text}.filter({$0 == true}).isEmpty
```suggestion
        let isFree = categories.map { $0.title == text }.filter({ $0 }).isEmpty
```

2023-02-14 20:34 UTC, IBDesignable commented on Tracker/Scenes/Trackers Flow/Category settings/CategorySettingsViewController.swift
> +        if text != "", Array(text).count < 39, isFree {
!text.isEmpty
text.count

isFree – мы за что- то платим в приложении?

2023-02-14 20:34 UTC, IBDesignable commented on Tracker/Scenes/Trackers Flow/Category settings/CategorySettingsViewController.swift
> +        if !isFree {
isUsed/isAvailable - что-то из этого подходит?

2023-02-14 20:34 UTC, IBDesignable commented on Tracker/Scenes/Trackers Flow/Category settings/CategorySettingsViewController.swift
> +        } else if Array(text).count > 38 {
магические числа – константы, о которых никому не известно. Давай вынесем в приватный список enum Constants и именуем понятно

2023-02-14 20:34 UTC, IBDesignable commented on Tracker/Scenes/Trackers Flow/Category settings/CategorySettingsViewController.swift
> +    func hideKeyboardWhenTappedAround() {
точно не стоит сделать приватным?

2023-02-14 20:34 UTC, IBDesignable commented on Tracker/Scenes/Trackers Flow/Trackers/TrackersViewController.swift
> +extension TrackersViewController: UICollectionViewDelegateFlowLayout {
Обычно когда очень большой контроллер получается по логике, выносят реализацию делегатов и датасурсов в отдельные файлы, можно даже свой класс создать, с близкой логикой к определенному контроллеру. 

Так мы разгружаем очень большие и массивные сущности

2023-02-14 20:34 UTC, IBDesignable commented on Tracker/Scenes/Trackers Flow/Trackers/TrackersViewController.swift
> +    private var interitemSpacing: CGFloat { return 9}
```suggestion
    private var interitemSpacing: CGFloat { return 9 }
```

2023-02-14 20:34 UTC, IBDesignable commented on Tracker/Scenes/Trackers Flow/Trackers/TrackersViewController.swift
> +            collectionView.reloadItems(at: [indexPath])
здесь бы создать функцию с аргументами

2023-02-14 20:34 UTC, IBDesignable commented on Tracker/Scenes/Trackers Flow/Trackers/TrackersViewController.swift
> +        let numberOfCompleted = completedTrackers.filter{$0.id == tracker.id}.count
Мне не очень нравится использование в качестве id - Double. Вряд ли кому-то в голову придет заводить идендификатор равный 3.14 :) 

Хорошими примерами id могут быть: UInt и UUID (можно хранить в базе как строку – уникальный-рандомный идендификатор)

2023-02-14 20:34 UTC, IBDesignable commented on Tracker/Scenes/Trackers Flow/TrackerSettings/TrackerSettingsViewController.swift
> +        }
Можно попробовать смапать и использовать joined для этой задачи 

https://developer.apple.com/documentation/swift/sequence/joined(separator:)-5zjyj

2023-02-14 20:34 UTC, IBDesignable commented on Tracker/Scenes/Trackers Flow/Schedule/ScheduleViewController.swift
> +            weekTableView.trailingAnchor.constraint(equalTo: view.trailingAnchor),
отступы не по макету

2023-02-14 20:41 UTC, IBDesignable commented
Сравнение с макетами:
плейсхолдер, цвет tint +, отсутствие ошибки на 38 символов, таблица. 

Плюс на скринах нет, но я бы еще проверила заблоченный цвет у кнопок  Создать с макетами.
<img width="310" alt="Снимок экрана 2023-02-14 в 22 39 10" src="https://user-images.githubusercontent.com/121577115/218857616-2c3d2a10-83ea-48a4-9f94-8ee6d31eef4e.png">
<img width="304" alt="Снимок экрана 2023-02-14 в 22 38 26" src="https://user-images.githubusercontent.com/121577115/218857631-865a7e1a-0318-440e-b4dd-28b57cd12493.png">
<img width="300" alt="Снимок экрана 2023-02-14 в 22 36 50" src="https://user-images.githubusercontent.com/121577115/218857641-5d2bc1e5-bf93-474d-850c-7572fc221f24.png">

2023-02-15 07:51 UTC, Filosuf commented
Александра, очень рад, что ты проверяла мою работу. Ты однозначно лучшая, твои комментарии очень полезны для меня и поучительны, другие просто бы не обратили бы внимание например на пробелы у скобок или названия функций. Теперь про критические замечания:
1. Нам про то каким должен быть id не рассказывали в лекциях и в тех заданиях ограничений на него не накладывали. Поэтому непонятно почему эта ошибка стала блокирующей. Я конечно же согласен, что Double не лучшее решение, посмотрю про UUID, но мне показалось хорошим решением применить время в качестве id.
2. Жаль, что ревьюеров нет в нашем чате в пачке. Задавал вопрос как выглядит отметка о выполнении и как ее убирать из ячейки наставнику, указывал на то, что описание не соответствует дизайну. На что наставник, как хороший продавец плохого товара брак не признает и говорит, что всё хорошо. Отметкой о выполнении предлагает считать счётчик дней/раз. А фразу "...убирает пометку о выполненности в ячейке трекера..." разьясняет как "... убирает пометку... на отдельном экране редактирования привычки." Так как этот экран мы еще не реализовывали, то и убирать отметку пока не можем. Прилагаю скриншот переписки из пачки: https://ltdfoto.ru/image/iBMD2u

2023-02-15 08:02 UTC, Filosuf commented on Tracker/Coordinators/MainCoordinator.swift
> +            return "Статистика"
Пока была цель сделать красивые окончания для дней/раз, цели использовать приложение на разных языках не было

2023-02-15 08:04 UTC, Filosuf commented on Tracker/Coordinators/MainCoordinator.swift
> +    var pageTitle: String {
вроде бы рядом, или непосредственно в class перенести?

2023-02-15 08:08 UTC, Filosuf commented on Tracker/Coordinators/MainCoordinator.swift
> +    // показать либо экран авторизации, либо новостную ленту
это проблемы копирования из другого проекта, исправил

2023-02-15 08:15 UTC, Filosuf commented on Tracker/Coordinators/MainCoordinator.swift
> +        tabBarVC.setViewControllers(pages.map { getNavController(page: $0) }, animated: true)
Спасибо, с `allCases` интересно. Исправил

2023-02-15 08:15 UTC, Filosuf commented on Tracker/Coordinators/MainCoordinator.swift
> +final class MainCoordinatorImp: MainCoordinator {
Спасибо

2023-02-15 08:19 UTC, Filosuf commented on Tracker/Models/DayOfWeek.swift
> +    static func <(lhs: DayOfWeek, rhs: DayOfWeek) -> Bool {
✔

2023-02-15 08:28 UTC, Filosuf commented on Tracker/Models/DayOfWeek.swift
> +    static func getWeek() -> [DayOfWeek] {
✔

2023-02-15 08:47 UTC, Filosuf commented on Tracker/Scenes/Trackers Flow/Category settings/CategorySettingsViewController.swift
> +        taps()
✔

2023-02-15 08:48 UTC, IBDesignable commented on Tracker/Coordinators/MainCoordinator.swift
> +            return "Статистика"
Верно, локализация не всегда нужна. 

Однако это способ хранения и переиспользования, так как текст как картинки и цвета – ресурс

2023-02-15 08:49 UTC, IBDesignable commented on Tracker/Coordinators/MainCoordinator.swift
> +    var pageTitle: String {
прости за неточность) 

Положить рядом в смысле отдельным файлом

2023-02-15 08:50 UTC, IBDesignable commented on Tracker/Scenes/Trackers Flow/Category settings/CategorySettingsViewController.swift
> +        }
не дочитала к тому моменту – думала что это апишка кнопки, а это твоя обертка :)

2023-02-15 08:57 UTC, IBDesignable commented
>  Я конечно же согласен, что Double не лучшее решение, посмотрю про UUID, но мне показалось хорошим решением применить время в качестве id.

Про время я похоже где-то пропустила, не увидела связь - покажи пожалуйста. 

Однако все же для id есть устоявшиеся правила, как контракт. Например, если ты захочешь общаться с бекендом и хранить заметки на сервере – бекендер тебе спасибо за дабл не скажет. Поэтому я пометила это как критичный момент, в жизни бы тебя с этим в прод не пустили. То есть даже если сейчас нет предпосылок, что надо будет общаться с бекендом – это все равно решение не масштабируется. Тем же базам данных легче работать с UInt или UUID (а база у вас в следующем спринте как раз). 

 А то что в учебнике нет, так это спасибо за фидбек! отдам авторам, обязательно допишем) 

Ну а про отмену отметки – я еще не получила комментария и сама не поняла как это должно быть сделано, поэтому возможно это лишний пункт в этом спринте, согласна принять без доработки этот пункт 👍🏻

2023-02-15 09:35 UTC, Filosuf commented
Date().timeIntervalSince1970 [ссылка](https://github.com/Filosuf/Tracker/blob/ffd26b5aa0a11138e3bc2c523b74b32fcd680219/Tracker/Scenes/Trackers%20Flow/TrackerSettings/TrackerSettingsViewController.swift#L205) округлять до `Int` не стал, боясь что пользователь за 1 секунду сможет создать 2 трекера.

2023-02-15 09:38 UTC, Filosuf commented on Tracker/Coordinators/MainCoordinator.swift
> +    var pageTitle: String {
✔

2023-02-15 11:05 UTC, Filosuf commented on Tracker/Scenes/Trackers Flow/Category settings/CategorySettingsViewController.swift
> +        }
✔

2023-02-15 11:27 UTC, Filosuf commented on Tracker/Scenes/Trackers Flow/Category settings/CategorySettingsViewController.swift
> +            let categoriesFiltered = categories.filter{$0 != category}
✔

2023-02-15 11:27 UTC, Filosuf commented on Tracker/Scenes/Trackers Flow/Category settings/CategorySettingsViewController.swift
> +        let isFree = categories.map{$0.title == text}.filter({$0 == true}).isEmpty
✔

2023-02-15 11:27 UTC, Filosuf commented on Tracker/Scenes/Trackers Flow/Category settings/CategorySettingsViewController.swift
> +        if text != "", Array(text).count < 39, isFree {
✔

2023-02-15 11:27 UTC, Filosuf commented on Tracker/Scenes/Trackers Flow/Category settings/CategorySettingsViewController.swift
> +        if !isFree {
✔

2023-02-15 11:32 UTC, Filosuf commented on Tracker/Scenes/Trackers Flow/Category settings/CategorySettingsViewController.swift
> +        var categoriesUpdated = [TrackerCategory]()
Если на работе попросят переучиваться то сделаю, пока так уже привык, надеюсь это некритично. Мне кажется логичным не указывать тип при начальном значении. Поэтому когда появляется `=` тип через `:` указывать тип уже не хочется.

2023-02-15 11:36 UTC, Filosuf commented on Tracker/Scenes/Trackers Flow/Category settings/CategorySettingsViewController.swift
> +        } else if Array(text).count > 38 {
этот список нужно создать внутри класса или один на всё приложение?

2023-02-15 11:37 UTC, Filosuf commented on Tracker/Scenes/Trackers Flow/Category settings/CategorySettingsViewController.swift
> +    func hideKeyboardWhenTappedAround() {
✔

2023-02-15 11:40 UTC, Filosuf commented on Tracker/Scenes/Trackers Flow/Trackers/TrackersViewController.swift
> +    private var interitemSpacing: CGFloat { return 9}
✔

2023-02-15 11:41 UTC, Filosuf commented on Tracker/Scenes/Trackers Flow/Trackers/TrackersViewController.swift
> +extension TrackersViewController: UICollectionViewDelegateFlowLayout {
Надо обдумать, примеры какие-то посмотреть. Может потом на рефакторинге. Сейчас не готов это сделать.

2023-02-15 11:49 UTC, Filosuf commented on Tracker/Scenes/Trackers Flow/Trackers/TrackersViewController.swift
> +            collectionView.reloadItems(at: [indexPath])
✔

2023-02-15 12:45 UTC, Filosuf commented on Tracker/Scenes/Trackers Flow/Trackers/TrackersViewController.swift
> +        let numberOfCompleted = completedTrackers.filter{$0.id == tracker.id}.count
✔

2023-02-15 12:53 UTC, Filosuf commented on Tracker/Scenes/Trackers Flow/TrackerSettings/TrackerSettingsViewController.swift
> +        }
✔

2023-02-15 12:56 UTC, IBDesignable commented on Tracker/Scenes/Trackers Flow/Category settings/CategorySettingsViewController.swift
> +        } else if Array(text).count > 38 {
смотря как часто используется эта константа. Здесь внутри класса уместнее.

2023-02-15 13:01 UTC, IBDesignable commented
Получила комментарий от авторов:

> - Надо делать в текущем спринте. пользователь кликает на кнопку "+" внутри ячейки трекера, она заменяется на галочку (сделано),  текст изменяется соотв. образом (было "2 раз" -> стало "3 раз"). Если в ячейке уже стоит галочка ,а не "+", то клик на нее приводит к обратному действию: галочка заменяется на "+" и "х раз" уменьшается на единицу. 

Предположу, что в день можно сделать только один раз действие выполнения привычки, поэтому инкрементация практически равна наличию Record за текущую даты.

2023-02-15 13:05 UTC, Filosuf commented on Tracker/Scenes/Trackers Flow/Schedule/ScheduleViewController.swift
> +            weekTableView.trailingAnchor.constraint(equalTo: view.trailingAnchor),
✔

2023-02-16 10:33 UTC, Filosuf commented on Tracker/Coordinators/MainCoordinator.swift
> +            return "Статистика"
✔

2023-02-16 20:46 UTC, IBDesignable approved these changes
Спасибо, принимаю :)

2023-02-16 20:46 UTC, IBDesignable commented on Tracker/Scenes/Trackers Flow/Category settings/CategorySettingsViewController.swift
> +        var categoriesUpdated = [TrackerCategory]()
Не критично, хорошо если на работе есть гайд что так принято :) переучиваться не надо

2023-02-16 20:46 UTC, IBDesignable commented on Tracker/Scenes/Trackers Flow/TrackerSettings/TrackerSettingsViewController.swift
> +    }
Похоже не нужен метод здесь

2023-02-16 20:46 UTC, IBDesignable commented on Tracker/Scenes/Trackers Flow/TrackerSettings/TrackerSettingsViewController.swift
> +            if warningLabel.isHidden {
так как внутри нет блока else, то стоит объединить, чтобы лишних операций не делать
```suggestion
        } else if warningLabel.isHidden {
```

2023-02-16 20:46 UTC, IBDesignable commented on Tracker/Scenes/Trackers Flow/Trackers/TrackersViewController.swift
>          trackers = trackers.sorted(by: <)
очень длинные цепочки. Так стараются не писать именно потому, что ну никто не будет разбирать что тут написано :) Код для людей! надо упрощать

Если тут сборное условие – то делят на переменные. Здесь фильтрация, поэтому я бы разобрала внутренние части и добавила их в вычислимые свойства или функции объекта tracker

`($0.schedule.contains(where: { $0.dayNumberOfWeek == currentDate.dayNumberOfWeek() })`
Вот тут хорошо разбивается на `hasScheduleDay(day: ...)`, можно добавить такую хелпер функцию к трекеру

`$0.schedule.isEmpty` -> `scheduleIsEmpty` как свойство у трекера, обращаться к своему свойству чтобы быть лаконичнее 

`($0.name.contains(textOfSearchQuery) || textOfSearchQuery == "") `:
вот тут  `textOfSearchQuery == ""` - возможно можно сделать отдельной строчкой кода, смотря что она должна была делать (мне показалось что для фильтрации объектов она не очень важна), ну и конечно не надо сравнивать с пустой строкой, когда есть isEmpty 
и последний $0.name.contains(textOfSearchQuery) тоже хорошо выносится в функцию `isContained(value: String)`


В общем, фильтрация никогда не являлась простой задачей, но чем понятнее и читаемее, по-шагам, ты ее распишешь – тем дешевле тебе будет это поддерживать и отлаживать. Это слабое место в твоем коде – старайся бить на этапы логические операции

2023-03-31 14:03 UTC, merged